server:
  port: 8080 #微服务端口
  server_name: userService #微服务名称
discover:
  consul: #consul实现
    ip: 127.0.0.1 #注册中心地址
    port: 8500 #注册中心端口
    tag:
      - userService #服务标签
    weight: 1 #权重，使用加权轮询时需要使用此项
jeager:
  enabled: true #是否启用jeager全链路追踪 true：启用，否则都是不启用
  url: 127.0.0.1:6831 #jeager地址
  type: const # const 固定采样
  param: 1 # 1:全采样，0:不采样
db:
  mysql:
    url: 10.0.0.133:3326 #mysql地址
    username: root #账号
    password: root #密码
    schema: test #缺省schema
    max_idle_conn: 10 #最大闲置连接
    max_open_conn: 100 #最大打开连接
    log_path: ./log/common/mysql.log #执行sql后的日志记录路径
  redis:
    redis_alone: #单机版
      enabled: true #是否启用，true：启用，false：不启用
      url: 10.0.0.244
      port: 6382
      password: ""
    redis_cluster: #集群版
      enabled: true #是否启用，true：启用，false：不启用
      password: ""
      redis_cluster_info:
        - { url: 10.0.0.244, port: 6381 }
        - { url: 10.0.0.244, port: 6382 }
        - { url: 10.0.0.244, port: 6383 }
        - { url: 10.0.0.244, port: 6384 }
        - { url: 10.0.0.244, port: 6385 }
        - { url: 10.0.0.244, port: 6386 }